### ISSUE TITLE
How to develop with appengine:devserver

### ISSUE THREAD

**Issue by HarisHashim** [scratches/spring-boot-sample-gae#11]
Hello everyone,

I have no idea how to run this sample project from eclipse. 

Normal appengine project is run using "mvn appengine:devserver" or in Eclipse case configure a Run Configuration for Maven Build using appengine:devserver as goals (Run => Run Configurations... => Maven Build => create new, select the project and type the goal).

I use appengine:devserver goal with other not spring boot project and it works.

I use spring-boot:run goal with the sample project and that works.

So I wonder if the right way to run sample project is spring-boot:run ? Instead of appengine:devserver ?

Which bring me to my next question. AFAIK the devserver actually emulate App Engine stuff like datastore in the development environment.

So without it, does that means we dont have access to appengine datastore?

If we can, how to do it using spring-boot:run etc?

TIA
Haris

**Comment by HarisHashim** [comment]
Running the sample project using appengine:devserver will actually result to successful run but when accessing

http://localhost:8080

I got this error:

`Problem accessing /. Reason:

    javax.servlet.http.HttpServletRequest.isAsyncStarted()Z

Caused by:

java.lang.NoSuchMethodError: javax.servlet.http.HttpServletRequest.isAsyncStarted()Z
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:107)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)`

From googling this looks like servlet version incompatibility issue.
